"""Visa Token Service and agent mandates: the two halves of scoped authority.

SIMULATION. No Visa endpoint is contacted, no card is enrolled anywhere, and
every token below is generated by this process. What is faithful is the shape
of the trust relationship, which is the part worth modelling:

  A PAN is a bearer credential with no scope. Anyone holding those 16 digits
  can charge any amount, at any merchant, forever, and the only remedy is to
  cancel the card. Handing that to an autonomous agent is indefensible - not
  because the agent is malicious, but because a prompt-injected agent, a
  logged request or a compromised process then has unlimited spending power.

  A network token is a different credential for the same funding account,
  issued per-context and revocable independently. `presentationType: AI_AGENT`
  is the context that says "an agent will present this, not a human at a
  terminal", and it carries a mandate: what the agent may buy, up to how much,
  from whom, until when.

The security property that matters: REVOCATION IS INDEPENDENT OF THE CARD.
A user who thinks the agent is misbehaving revokes the mandate and keeps
paying for lunch with the same physical card five seconds later. Compare with
handing over a PAN, where the only kill switch is cancelling the card and
re-entering it in twenty other places.

WHAT IS REAL HERE:
  - Mandates are signed (HMAC-SHA256 JWS-style) and verified on every use.
    The agent holds a bearer credential it cannot forge or widen.
  - Every constraint is enforced at the rail, in `authorize_token_use`, not
    in the UI. A client that skips the frontend gets the same refusals.
  - Cumulative spend is tracked, so a cap is a real ceiling rather than a
    per-transaction check an agent can defeat by splitting the order.
  - Revocation is checked at authorization time, so a mandate revoked between
    preview and charge stops the charge.
  - Token cryptograms are single-use and bound to one authorization.

WHAT IS NOT:
  - The signing key is process-local, not an HSM. Real mandate signing happens
    in tamper-resistant hardware at the network.
  - There is no real funding account behind any of these tokens.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import secrets
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

log = logging.getLogger("roomhack.vts")

# Process-local signing key. Regenerated per boot, which means mandates do not
# survive a restart - correct for a demo, and it makes the point that the key
# is the root of trust for every mandate.
_SIGNING_KEY = secrets.token_bytes(32)

# How long an agent mandate stays valid without renewal. A standing permission
# to spend should expire on its own; a mandate the user forgot they granted is
# the failure mode this guards against.
DEFAULT_MANDATE_TTL_SECONDS = 24 * 60 * 60

# Token cryptograms are single-use and short-lived, like a real dTVV.
CRYPTOGRAM_TTL_SECONDS = 5 * 60


class PresentationType(str, Enum):
    """How the token will be presented. AI_AGENT is the one that matters here:
    it tells the network no human is at the point of sale, which changes both
    the liability model and the checks the issuer applies."""

    ECOMMERCE = "ECOMMERCE"
    AI_AGENT = "AI_AGENT"


class TokenStatus(str, Enum):
    ACTIVE = "active"
    SUSPENDED = "suspended"
    REVOKED = "revoked"       # user pulled the mandate; card itself unaffected
    EXPIRED = "expired"


class MandateViolation(Exception):
    """The mandate forbids this. Carries an HTTP status and a machine code so
    the UI can explain precisely which guardrail fired."""

    def __init__(self, status: int, code: str, detail: str) -> None:
        super().__init__(detail)
        self.status = status
        self.code = code
        self.detail = detail


# --- Merchant category codes ----------------------------------------------
#
# Real MCCs. 5712 is furniture, 5713 floor covering, 5719 home furnishing,
# 5200 home supply. The category lock is expressed in these rather than in
# merchant names because a name check is defeated by a merchant renaming
# itself, and because MCC is what actually travels on the authorization.

MCC_FURNITURE = "5712"
MCC_FLOOR_COVERINGS = "5713"
MCC_HOME_FURNISHING = "5719"
MCC_HOME_SUPPLY = "5200"
MCC_LIGHTING = "5065"

HOME_CATEGORY_MCCS: frozenset[str] = frozenset(
    {MCC_FURNITURE, MCC_FLOOR_COVERINGS, MCC_HOME_FURNISHING, MCC_HOME_SUPPLY, MCC_LIGHTING}
)

# Which MCC each merchant in the catalog transacts under. A merchant absent
# from this map has no known category, and an unknown category fails the
# category lock rather than passing it - the safe direction for a check whose
# whole purpose is to constrain what an agent may buy.
MERCHANT_MCC: dict[str, str] = {
    "IKEA": MCC_HOME_FURNISHING,
    "Castlery": MCC_FURNITURE,
    "HipVan": MCC_HOME_FURNISHING,
    "Commune": MCC_FURNITURE,
    "Scanteak": MCC_FURNITURE,
    "FortyTwo": MCC_HOME_FURNISHING,
    "Courts": MCC_HOME_SUPPLY,
}


def mcc_for_merchant(merchant: str) -> str | None:
    return MERCHANT_MCC.get(merchant)


# --- Mandate ---------------------------------------------------------------


@dataclass
class AgentMandate:
    """The scope of authority a user delegates to the agent.

    Every field is a limit the user set and can change. Together they answer
    "what is the worst this agent can do with my money" with a specific number
    rather than a hope.
    """

    id: str
    # Per-transaction ceiling. The agent cannot assemble a single order above
    # this, full stop.
    per_transaction_cap_cents: int
    # Lifetime ceiling across every transaction on this mandate. Without this,
    # a per-transaction cap is defeated by making many transactions.
    cumulative_cap_cents: int
    spent_cents: int = 0
    # MCC allowlist. Empty means "no category restriction", which we never use
    # by default - an unrestricted agent token is barely better than a PAN.
    allowed_mccs: frozenset[str] = field(default_factory=lambda: HOME_CATEGORY_MCCS)
    # Optional merchant allowlist, tighter than the category lock.
    allowed_merchants: frozenset[str] = field(default_factory=frozenset)
    # Maximum merchants in one order. An agent bundling twelve unknown shops
    # into one authorization is a signal worth capping.
    max_merchants_per_transaction: int = 5
    # Whether a passkey assertion is required before authorization. True for
    # any real mandate; the field exists so the requirement is explicit and
    # auditable rather than implied by code path.
    require_user_presence: bool = True
    created_at: float = 0.0
    expires_at: float = 0.0
    revoked_at: float | None = None
    revocation_reason: str = ""
    # Every use, for the audit trail the user reviews later.
    uses: list[dict[str, Any]] = field(default_factory=list)

    @property
    def remaining_cents(self) -> int:
        return max(0, self.cumulative_cap_cents - self.spent_cents)

    @property
    def active(self) -> bool:
        return self.revoked_at is None and time.time() < self.expires_at


@dataclass
class NetworkToken:
    """A scoped stand-in for a card, issued by the (simulated) token service.

    `token_last4` deliberately differs from the funding card's last4: that is
    true of real network tokens, and showing both is what lets a user match a
    statement line to the agent that created it.
    """

    token_id: str
    funding_method_id: str      # which stored card this token draws on
    token_last4: str
    presentation_type: PresentationType
    status: TokenStatus
    mandate: AgentMandate
    created_at: float
    # Token Assurance Level: how strongly the cardholder was verified when the
    # token was provisioned. 3-D Secure gives ~0x10; a device biometric via
    # FIDO gives the highest band. Real field, real semantics.
    assurance_level: int = 0
    assurance_method: str = "none"


TOKENS: dict[str, NetworkToken] = {}
# Single-use cryptograms, keyed by their own id.
CRYPTOGRAMS: dict[str, dict[str, Any]] = {}


def _now() -> float:
    return time.time()


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode().rstrip("=")


def _b64url_decode(data: str) -> bytes:
    return base64.urlsafe_b64decode(data + "=" * ((-len(data)) % 4))


# --- Mandate credential (signed, agent-held) -------------------------------


def sign_mandate(mandate: AgentMandate, token_id: str) -> str:
    """Produce the bearer credential the agent presents with every request.

    JWS-shaped: header.payload.signature, base64url, HMAC-SHA256. The agent
    holds this and cannot alter a single claim in it - raising its own spend
    cap requires the signing key, which lives only here.

    A real deployment signs with an asymmetric key in an HSM so that even this
    server cannot mint a mandate the user did not approve. HMAC is the honest
    simplification for a single-process demo, and it preserves the property
    that matters: the holder cannot widen its own scope.
    """
    header = {"alg": "HS256", "typ": "visa-agent-mandate+jwt"}
    payload = {
        "jti": mandate.id,
        "tok": token_id,
        "iat": int(mandate.created_at),
        "exp": int(mandate.expires_at),
        "scope": {
            "per_txn_cap": mandate.per_transaction_cap_cents,
            "cumulative_cap": mandate.cumulative_cap_cents,
            "mccs": sorted(mandate.allowed_mccs),
            "merchants": sorted(mandate.allowed_merchants),
            "max_merchants": mandate.max_merchants_per_transaction,
            "require_presence": mandate.require_user_presence,
        },
        "presentation_type": PresentationType.AI_AGENT.value,
    }
    signing_input = (
        _b64url(json.dumps(header, separators=(",", ":"), sort_keys=True).encode())
        + "."
        + _b64url(json.dumps(payload, separators=(",", ":"), sort_keys=True).encode())
    )
    signature = hmac.new(_SIGNING_KEY, signing_input.encode(), hashlib.sha256).digest()
    return f"{signing_input}.{_b64url(signature)}"


def verify_mandate_credential(credential: str) -> dict[str, Any]:
    """Verify the agent's credential and return its claims.

    Signature first, then expiry, then revocation. Signature first matters:
    claims from an unverified token are attacker-controlled, and reading them
    before checking the signature is how JWT implementations get broken.
    """
    parts = credential.split(".")
    if len(parts) != 3:
        raise MandateViolation(400, "malformed_mandate", "malformed mandate credential")
    signing_input = f"{parts[0]}.{parts[1]}"
    expected = hmac.new(_SIGNING_KEY, signing_input.encode(), hashlib.sha256).digest()
    try:
        provided = _b64url_decode(parts[2])
    except (ValueError, base64.binascii.Error) as exc:  # type: ignore[attr-defined]
        raise MandateViolation(400, "malformed_mandate", "malformed signature") from exc
    if not hmac.compare_digest(expected, provided):
        raise MandateViolation(
            403, "bad_signature", "mandate signature is invalid - refusing to spend"
        )

    try:
        claims = json.loads(_b64url_decode(parts[1]))
    except ValueError as exc:
        raise MandateViolation(400, "malformed_mandate", "malformed mandate claims") from exc

    if _now() > float(claims.get("exp", 0)):
        raise MandateViolation(
            410,
            "mandate_expired",
            "this spending mandate has expired - re-authorize with your passkey",
        )
    return claims


# --- Provisioning ----------------------------------------------------------


def provision_token(
    *,
    funding_method_id: str,
    per_transaction_cap_cents: int,
    cumulative_cap_cents: int,
    allowed_mccs: frozenset[str] | None = None,
    allowed_merchants: frozenset[str] | None = None,
    ttl_seconds: int = DEFAULT_MANDATE_TTL_SECONDS,
    max_merchants_per_transaction: int = 5,
    assurance_method: str = "fido2_device_biometric",
) -> tuple[NetworkToken, str]:
    """Enroll a card into the token service and mint a scoped AI_AGENT token.

    Returns the token and the signed mandate credential the agent will hold.
    Called only after a passkey assertion has proven the cardholder is present
    - provisioning an agent token is exactly as sensitive as the spending it
    later permits, so it gets the same proof.
    """
    if per_transaction_cap_cents <= 0 or cumulative_cap_cents <= 0:
        raise MandateViolation(
            400, "invalid_cap", "spend caps must be greater than zero"
        )
    # An absolute ceiling the client cannot argue with. The caps above are
    # whatever the caller asked for; this is the limit the deployment sets.
    from . import config

    ceiling = config.MAX_AGENT_MANDATE_CENTS
    if cumulative_cap_cents > ceiling or per_transaction_cap_cents > ceiling:
        raise MandateViolation(
            400,
            "cap_too_large",
            f"an agent mandate cannot exceed S${ceiling / 100:,.2f}",
        )
    if per_transaction_cap_cents > cumulative_cap_cents:
        # Otherwise the per-transaction cap is decorative: the cumulative cap
        # binds first and the number the user set is never the real limit.
        raise MandateViolation(
            400,
            "invalid_cap",
            "per-transaction cap cannot exceed the total cap",
        )

    now = _now()
    mandate = AgentMandate(
        id=f"mnd_{secrets.token_hex(8)}",
        per_transaction_cap_cents=per_transaction_cap_cents,
        cumulative_cap_cents=cumulative_cap_cents,
        allowed_mccs=allowed_mccs if allowed_mccs is not None else HOME_CATEGORY_MCCS,
        allowed_merchants=allowed_merchants or frozenset(),
        max_merchants_per_transaction=max_merchants_per_transaction,
        created_at=now,
        expires_at=now + ttl_seconds,
    )
    token = NetworkToken(
        token_id=f"vts_{secrets.token_hex(10)}",
        funding_method_id=funding_method_id,
        # Distinct from the funding card's last4, as a real token is.
        token_last4=f"{secrets.randbelow(10000):04d}",
        presentation_type=PresentationType.AI_AGENT,
        status=TokenStatus.ACTIVE,
        mandate=mandate,
        created_at=now,
        # Highest assurance band: the cardholder was verified by a device
        # biometric bound to a hardware-held key, not by a knowledge factor.
        assurance_level=0x20 if assurance_method.startswith("fido2") else 0x10,
        assurance_method=assurance_method,
    )
    TOKENS[token.token_id] = token
    credential = sign_mandate(mandate, token.token_id)
    log.info(
        "provisioned AI_AGENT token %s on %s: per-txn %d, total %d, mccs=%s",
        token.token_id,
        funding_method_id,
        per_transaction_cap_cents,
        cumulative_cap_cents,
        sorted(mandate.allowed_mccs),
    )
    return token, credential


def get_token(token_id: str) -> NetworkToken:
    token = TOKENS.get(token_id)
    if token is None:
        raise MandateViolation(404, "unknown_token", "unknown agent token")
    if token.status == TokenStatus.ACTIVE and not token.mandate.active:
        token.status = (
            TokenStatus.REVOKED
            if token.mandate.revoked_at is not None
            else TokenStatus.EXPIRED
        )
    return token


def revoke_token(token_id: str, reason: str = "revoked by user") -> NetworkToken:
    """Kill the agent's spending authority. The card is untouched.

    This is the property that makes delegating to an agent reversible: the
    user is cancelling a permission, not a payment instrument. Everything else
    the card pays for keeps working.
    """
    token = get_token(token_id)
    token.status = TokenStatus.REVOKED
    token.mandate.revoked_at = _now()
    token.mandate.revocation_reason = reason
    log.info("agent token %s REVOKED: %s", token_id, reason)
    return token


def list_tokens() -> list[NetworkToken]:
    for token_id in list(TOKENS):
        get_token(token_id)  # refresh lazily-expired statuses
    return list(TOKENS.values())


# --- Enforcement -----------------------------------------------------------


@dataclass
class MandateCheck:
    """The outcome of evaluating a proposed purchase against a mandate.

    Returned even when it passes, so the preview can show the user their
    remaining headroom rather than only shouting when something is wrong.
    """

    ok: bool
    token_id: str
    per_transaction_cap_cents: int
    cumulative_cap_cents: int
    spent_cents: int
    remaining_cents: int
    amount_cents: int
    allowed_mccs: list[str]
    merchant_mccs: dict[str, str]
    expires_at: float
    violations: list[dict[str, str]] = field(default_factory=list)


def evaluate(
    *,
    mandate_credential: str,
    merchants: list[str],
    amount_cents: int,
) -> MandateCheck:
    """Check a proposed purchase against the mandate WITHOUT consuming it.

    Used at preview time so the user sees the guardrails before authorizing.
    Collects every violation rather than stopping at the first, because a user
    who fixes one problem and is then shown a second has learned nothing about
    the limits they set.
    """
    claims = verify_mandate_credential(mandate_credential)
    token = get_token(str(claims.get("tok") or ""))
    mandate = token.mandate
    scope = claims.get("scope") or {}

    # The credential must name the mandate it was signed for, not just a
    # token. Otherwise a credential carrying mandate A's caps could be
    # evaluated against token B's live spend - unreachable today, since
    # `sign_mandate` is only ever called with a matched pair, but the pairing
    # is an invariant worth asserting rather than assuming.
    if str(claims.get("jti") or "") != mandate.id:
        raise MandateViolation(
            403, "mandate_mismatch", "mandate credential does not match this token"
        )

    violations: list[dict[str, str]] = []

    if token.status == TokenStatus.REVOKED:
        violations.append(
            {
                "code": "token_revoked",
                "detail": (
                    "You revoked this agent's spending mandate"
                    + (f" ({mandate.revocation_reason})" if mandate.revocation_reason else "")
                    + ". Your card itself is unaffected."
                ),
            }
        )
    elif token.status == TokenStatus.EXPIRED:
        violations.append(
            {
                "code": "mandate_expired",
                "detail": "This spending mandate has expired. Re-authorize with your passkey.",
            }
        )
    elif token.status == TokenStatus.SUSPENDED:
        violations.append(
            {"code": "token_suspended", "detail": "This agent token is suspended."}
        )

    # Read caps from the signed claims, not the in-memory object: the claims
    # are what the agent presented and what it is bound by. If the two ever
    # disagree, the signed value is authoritative.
    per_txn = int(scope.get("per_txn_cap") or mandate.per_transaction_cap_cents)
    cumulative = int(scope.get("cumulative_cap") or mandate.cumulative_cap_cents)

    if amount_cents > per_txn:
        violations.append(
            {
                "code": "over_per_transaction_cap",
                "detail": (
                    f"S${amount_cents / 100:,.2f} is over the "
                    f"S${per_txn / 100:,.2f} per-purchase limit you set for this agent."
                ),
            }
        )

    if mandate.spent_cents + amount_cents > cumulative:
        remaining = max(0, cumulative - mandate.spent_cents)
        violations.append(
            {
                "code": "over_cumulative_cap",
                "detail": (
                    f"This would take the agent past its S${cumulative / 100:,.2f} "
                    f"total budget. S${remaining / 100:,.2f} remains."
                ),
            }
        )

    allowed = frozenset(str(m) for m in (scope.get("mccs") or []))
    merchant_mccs: dict[str, str] = {}
    for merchant in merchants:
        mcc = mcc_for_merchant(merchant)
        merchant_mccs[merchant] = mcc or "unknown"
        if allowed and (mcc is None or mcc not in allowed):
            violations.append(
                {
                    "code": "category_locked",
                    "detail": (
                        f"{merchant} is not a furniture or home-decor merchant "
                        f"(category {mcc or 'unknown'}). This agent token is locked "
                        "to that category."
                    ),
                }
            )

    allowed_merchants = frozenset(str(m) for m in (scope.get("merchants") or []))
    if allowed_merchants:
        for merchant in merchants:
            if merchant not in allowed_merchants:
                violations.append(
                    {
                        "code": "merchant_not_allowed",
                        "detail": f"{merchant} is not on this agent's merchant allowlist.",
                    }
                )

    max_merchants = int(scope.get("max_merchants") or mandate.max_merchants_per_transaction)
    if len(set(merchants)) > max_merchants:
        violations.append(
            {
                "code": "too_many_merchants",
                "detail": (
                    f"{len(set(merchants))} merchants in one order exceeds the "
                    f"limit of {max_merchants} you set for this agent."
                ),
            }
        )

    return MandateCheck(
        ok=not violations,
        token_id=token.token_id,
        per_transaction_cap_cents=per_txn,
        cumulative_cap_cents=cumulative,
        spent_cents=mandate.spent_cents,
        remaining_cents=max(0, cumulative - mandate.spent_cents),
        amount_cents=amount_cents,
        allowed_mccs=sorted(allowed),
        merchant_mccs=merchant_mccs,
        expires_at=mandate.expires_at,
        violations=violations,
    )


def issue_cryptogram(
    *,
    token_id: str,
    intent_id: str,
    amount_cents: int,
    assertion_id: str,
) -> dict[str, Any]:
    """Mint a single-use token cryptogram for one authorization.

    Bound to (token, intent, amount, assertion). A real dTVV is bound the same
    way, which is why intercepting one buys an attacker nothing: it authorizes
    exactly one purchase, of exactly one amount, and only once.
    """
    cryptogram_id = f"tavv_{secrets.token_hex(6)}"
    material = f"{token_id}|{intent_id}|{amount_cents}|{assertion_id}|{cryptogram_id}"
    value = hmac.new(_SIGNING_KEY, material.encode(), hashlib.sha256).digest()
    CRYPTOGRAMS[cryptogram_id] = {
        "token_id": token_id,
        "intent_id": intent_id,
        "amount_cents": amount_cents,
        "assertion_id": assertion_id,
        "expires_at": _now() + CRYPTOGRAM_TTL_SECONDS,
        "used": False,
    }
    return {
        "cryptogram_id": cryptogram_id,
        # Displayed truncated, as a real cryptogram would be in any UI.
        "value": _b64url(value)[:22],
        "expires_at": CRYPTOGRAMS[cryptogram_id]["expires_at"],
    }


def consume_cryptogram(
    cryptogram_id: str, *, intent_id: str, amount_cents: int
) -> dict[str, Any]:
    """Spend a cryptogram. Single-use, amount-bound, time-boxed."""
    record = CRYPTOGRAMS.get(cryptogram_id)
    if record is None:
        raise MandateViolation(400, "unknown_cryptogram", "unknown token cryptogram")
    if record["used"]:
        raise MandateViolation(
            409, "cryptogram_replayed", "this token cryptogram was already used"
        )
    if _now() > record["expires_at"]:
        raise MandateViolation(
            410, "cryptogram_expired", "token cryptogram expired - re-authorize"
        )
    if record["intent_id"] != intent_id:
        raise MandateViolation(
            403, "cryptogram_mismatch", "cryptogram was issued for a different payment"
        )
    if record["amount_cents"] != amount_cents:
        raise MandateViolation(
            403,
            "cryptogram_mismatch",
            "cryptogram was issued for a different amount",
        )
    record["used"] = True
    return record


def reserve_spend(token_id: str, amount_cents: int) -> bool:
    """Claim headroom against the cumulative cap BEFORE charging.

    Checking the cap and then charging leaves a window: N intents priced
    against the same headroom each pass the check, and the cap - whose whole
    purpose is to stop an agent splitting one large order into many small
    ones - does not hold. Incrementing first closes it.

    Python's GIL makes this increment atomic between `await` points, and every
    caller runs it synchronously inside one request, so no explicit lock is
    needed here. A multi-process deployment would need the counter in shared
    storage with a real compare-and-set.
    """
    token = TOKENS.get(token_id)
    if token is None:
        return False
    mandate = token.mandate
    if mandate.spent_cents + amount_cents > mandate.cumulative_cap_cents:
        return False
    mandate.spent_cents += amount_cents
    return True


def release_spend(token_id: str, amount_cents: int) -> None:
    """Return reserved headroom that was not actually charged.

    Called when a leg declines. Holding a reservation for money that never
    moved would silently shrink the user's remaining budget.
    """
    token = TOKENS.get(token_id)
    if token is None:
        return
    token.mandate.spent_cents = max(0, token.mandate.spent_cents - amount_cents)


def record_spend(
    token_id: str, *, amount_cents: int, intent_id: str, order_id: str
) -> None:
    """Commit spend against the mandate's cumulative cap.

    Called only after money actually moves, and only for the approved portion:
    counting a declined charge against the user's budget would be wrong twice
    over - they did not spend it, and it would silently shrink their headroom.
    """
    token = TOKENS.get(token_id)
    if token is None:  # pragma: no cover - defensive
        return
    # NOT incremented here: `reserve_spend` already claimed this amount before
    # the charge loop ran, and any declined portion was released. Adding again
    # would double-count every purchase against the user's budget.
    token.mandate.uses.append(
        {
            "intent_id": intent_id,
            "order_id": order_id,
            "amount_cents": amount_cents,
            "at": _now(),
        }
    )
    log.info(
        "mandate %s: spent %d, total %d of %d",
        token.mandate.id,
        amount_cents,
        token.mandate.spent_cents,
        token.mandate.cumulative_cap_cents,
    )
